server:
  port: 801


spring:
  application:
    name: consumer-dept

eureka:
  client:
    service-url:
      defaultZone: http://Apanic:123456@eureka7001.com:7001/eureka/,http://Apanic:123456@eureka7002.com:7002/eureka/,http://Apanic:123456@eureka7003.com:7003/eureka/
  instance:
    instance-id:  新城桑consumer-dept-80
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

#引入feign才能用yml 配置
provider-dept:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule