server:
  port: 8001

mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
   # 所有entity别名类所在包
  type-aliases-package: com.cloud.entities
  # mapper映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
#  security:
#    user:
      #配置登录的账号
#      name: Apanic
      #配置登录的密码
#      password: 123456
  application:
    name: provider-dept
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    # 数据库名称
    url: jdbc:mysql://192.168.80.130:3306/cloudBD01?useSSL=false&allowMultiQueries=true
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 最大等待时间
      max-wait-millis: 200

logging:
  level:
    # 开启SQL日志，key为包名
    com.cloud.dao: debug
#debug: true

eureka:
  #客户端注册进Eureka服务列表内
  client:
    service-url:
      #集群 多个用 , 号分隔
      defaultZone: http://Apanic:123456@eureka7001.com:7001/eureka/,http://Apanic:123456@eureka7002.com:7002/eureka/,http://Apanic:123456@eureka7003.com:7003/eureka/
  instance:
     #hystrix相关服务别名
    instance-id: 张畅君provider-dept:8001-hystrix
    #访问路径可以显示IP地址
    prefer-ip-address: true

management:
  endpoint:
    health:
       # 是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        #暴露端点给hystrix监控,可以'*'
        include: hystrix.stream,info,metrics
#上面 info 端点 自定义信息
info:
  app.name: parentcloud
  company.name: www.morev.com
  my.name: 畅畅桑
  build.artifactid: $project.artifactId$
  build.version: $project.version$