server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml                                             # mybatis配置文件所在路径
  type-aliases-package: com.cloud.entities                                                      # 所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                                              # mapper映射文件


spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                                                 # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                                                #  数据库驱动包
    username: root
    password: password
    url: jdbc:mysql://192.168.80.130:3306/cloudBD01?useSSL=false&allowMultiQueries=true         # 数据库名称
    dbcp2:
      min-idle: 5                                                                              # 数据库连接池的最小维持连接数
      initial-size: 5                                                                         # 初始化连接数
      max-total: 5                                                                            # 最大连接数
      max-wait-millis: 200                                                                   # 最大等待时间

logging:
  level:
    com.cloud.dao: debug                                                                     # 开启SQL日志
#debug: true

eureka:
  client:                                                                                    #客户端注册进Eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: 张畅君provider-dept:8001-hystrix                                                   #hystrix相关服务别名
    prefer-ip-address: true                                                                        #访问路径可以显示IP地址

management:
  endpoint:
    health:
       # 是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        #暴露端点给hystrix监控,可以'*'
        include: hystrix.stream,info,metrics

info:
  app.name: parentcloud
  company.name: www.morev.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$