spring:
  security:
    user:
      #配置登录的账号
      name: Apanic
      #配置登录的密码
      password: 123456
server:
  port: 7003
eureka:
  server:
    enable-self-preservation: true          #自我保护
  instance:
    hostname: eureka7003.com                     #eureka 服务端的实例名称
    preferIpAddress: true
  client:
    register-with-eureka: false            #false 表示不向注册中心注册自己
    fetch-registry: false                    #false 表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    #设置与eureka server交互的地址查询服务和注册服务
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka7001.com:7001/eureka,http://${spring.security.user.name}:${spring.security.user.password}@eureka7002.com:7002/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/