server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Apamic/cloud-config.git                                        #git 上的仓库名字





