eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: 瞬凯桑gateway-9527.com
    prefer-ip-address: true

info:
  app.name: com.cloud
  company.name: www.morev.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: zuul-gateway

server:
  port: 9527

